### PR TITLE
Fix CRC DR read if peripheral clock is disabled

### LINKED ISSUE #82: [BUG] HW CRC32 calculation works even without clock enabled
**Describe the bug**
Real HW requires calling `__HAL_RCC_CRC_CLK_ENABLE();` prior to using CRC32 calculation, but on the simulator it works even without enabling the clock.

**To Reproduce**
```
static inline uint32_t crc32(const uint32_t *buffer, uint32_t length) {
  CRC->CR = CRC_CR_RESET;
  while (length--) {
    const uint32_t word = *((uint32_t *)buffer++);
    CRC->DR = __RBIT(word);
  }
  return __RBIT(CRC->DR) ^ 0xFFFFFFFF;
}
```

**Expected behavior**
Mentioned function should return 0xFFFFFFFF unless `__HAL_RCC_CRC_CLK_ENABLE();` is called prior to calling the function.

### PR DESCRIPTION
**Pull request by vintagepc**
### Description

Fix for #82 

### Behaviour/ Breaking changes

CRC DR now returns ~0xFFFFFFFF~ 0 if the clock is disabled.

### Other

Fixes a memory leak in the IWDG reset function.

### Linked issues:

 - Closes #82 
- Partial for #81

### CODE REVIEW

File: hw/arm/prusa/stm32f407/stm32f2xx_crc.c [hunk 1]
```diff
@@ -123,7 +124,14 @@ f2xx_crc_read(void *arg, hwaddr addr, unsigned int size)
...
     switch(addr) {
     case R_CRC_DR:
-        return s->crc;
+        if (s->rcc && stm32_rcc_check_periph_clk(s->rcc, STM32_CRC)) 
+        {
+            return s->crc;
+        }
+        else
+        {
+            return 0xFFFFFFFFU;
```
Comment (milosfec) [inline hw/arm/prusa/stm32f407/stm32f2xx_crc.c:133]: I could have mentioned it in the bug report, we need to invert the result (it's done in the implementation I wrote within the bug report). Function is returning 0xFFFFFFFF because CRC DR returns 0 :)
